version: "3.3"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      API_ID: 29728482
      API_HASH: 7172d0ad38f2c24bbf482a72f39a8be2 # Your API ID from my.telegram.org
      BOT_TOKEN: 6744155888:AAFvtXfSNIlrKkRUTKfzU1FNo-lbOdJ3SmU # Bot token, get it from @BotFather 
      SESSION:  # Pyrogram string session
      AUTH:  # User ID of Bot owner
      FORCESUB:  # Username name of public channel without using '@'
